---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "shrtn.fullname" . }}
  labels:
    {{- include "shrtn.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}