name: Build and Upload on Tag

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
  push:
    tags:
      - 'v*'
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  PUBLIC_FEATURE_MARKETING_PAGES: 'off'
jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up the required language/environment
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      # Install dependencies and build the project
      - name: Install dependencies
        run: bun install

      - name: Build the project
        run: bun run build # Adjust the build command to suit your project

      - name: Zip file
        run: cd build && zip -r ../shrtn.zip * && cd .. && zip shrtn.zip package.json bun.lock drizzle/**/* drizzle.config.ts

      # Upload the build artifact
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag || github.ref_name }}
          release_name: Release ${{ inputs.tag || github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./shrtn.zip # Adjust this to your artifact path
          asset_name: shrtn.zip # Adjust the name as required
          asset_content_type: application/zip
