name: Version

on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
  attestations: write
  deployments: write
concurrency: ${{ github.workflow }}-${{ github.ref }}
env:
  PUBLIC_FEATURE_MARKETING_PAGES: 'on'
jobs:
  release:
    name: Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        # with:
        #   # This expects you to have a script called release which does a build for your packages and calls changeset publish
        #   publish: bun run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
