name: Deploy to Cloudflare Workers

on:
  workflow_call:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
env:
  PUBLIC_FEATURE_MARKETING_PAGES: 'on'
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - name: bun-setup
        uses: oven-sh/setup-bun@v2
      - name: Install Dependencies
        run: bun install
      - name: Build
        run: bun run build:cloudflare
      - name: Migrate
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: bun
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: d1 migrations apply SHRTN_D1
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: bun
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
          secrets: |
            MAILGUN_API_KEY
            MAILGUN_DOMAIN
        env:
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
