name: Release

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
  packages: write
  attestations: write
  id-token: write
  deployments: write
concurrency: ${{ github.workflow }}-${{ github.ref }}
env:
  PUBLIC_FEATURE_MARKETING_PAGES: 'on'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.push_tags.outputs.tag}}
    steps:
      - uses: actions/checkout@v4
      - name: Push Tags
        id: push_tags
        run: |
          set +e
          TAG=$(jq -r .version < package.json)
          if git ls-remote --exit-code --tags origin "refs/tags/v$TAG" >/dev/null; then
            echo "Tag v$TAG already exists"
          else
            git tag "v$TAG"
            git push origin "v$TAG"
            echo "tag=v$TAG" >> "$GITHUB_OUTPUT"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  call-docker-push:
    needs: release
    if: needs.release.outputs.tag != ''
    uses: ./.github/workflows/docker-publish.yml
    with:
      tag: ${{ needs.release.outputs.tag }}
    secrets: inherit
  call-chart-bump:
    needs: release
    if: needs.release.outputs.tag != ''
    uses: ./.github/workflows/set_app_version.yml
    with:
      tag: ${{ needs.release.outputs.tag }}
    secrets: inherit
  call-build:
    needs: release
    if: needs.release.outputs.tag != ''
    uses: ./.github/workflows/build.yml
    with:
      tag: ${{ needs.release.outputs.tag }}
    secrets: inherit
  call-deploy:
    needs: release
    if: needs.release.outputs.tag != ''
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
