name: Release

on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: bun-setup
        uses: oven-sh/setup-bun@v2
      - name: Install Dependencies
        run: bun install
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: bun run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Push Tags
        run: |
          set +e
          TAG=$(jq -r .version < package.json)
          git show-ref --tags --verify --quiet "v$TAG"
          if [ $? -eq 1 ]; then
            echo "Tag already exists"
          else
            git tag "v$TAG"
            git push origin "v$TAG"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
