name: Test
on: [push]

jobs:
  test-local:
    services:
      mailpit:
        image: axllent/mailpit
        ports:
          - 8025:8025
          - 1025:1025
    name: Test and Build
    runs-on: ubuntu-latest
    env:
      DATABASE_TYPE: libSQL
      DATABASE_URL: file:local.db
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun run build
      - name: Prepare playwright
        run: bunx playwright install
      - name: Run all Tests
        run: bun run test
        env:
          MAILPIT_DOMAIN: http://localhost:8025
          MAIL_FROM: noreply@shrtn.io
          ORIGIN: http://localhost:4173
      - name: Test SMTP
        run: bun run test:e2e:smtp
        env:
          MAIL_PROVIDER: smtp
          MAIL_HOST: localhost
          MAIL_PORT: 1025
          MAIL_FROM: noreply@shrtn.io
          ORIGIN: http://localhost:4173
  test-cloudflare:
    name: Test and Build
    runs-on: ubuntu-latest
    services:
      mailpit:
        image: axllent/mailpit
        ports:
          - 8025:8025
          - 1025:1025
    env:
      DATABASE_TYPE: d1
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun run build
      - name: Prepare playwright
        run: bunx playwright install
      - name: Run all Tests
        run: bun run test:e2e:cloudflare
        env:
          MAILPIT_DOMAIN: http://localhost:8025
          MAIL_FROM: noreply@shrtn.io
          ORIGIN: http://localhost:4173
