name: Test
on: [push]

jobs:
  test-local:
    services:
      mailpit:
        image: axllent/mailpit
        ports:
          - 8025:8025
          - 1025:1025
    name: Test and Build - Local
    runs-on: ubuntu-latest
    env:
      DATABASE_TYPE: libSQL
      DATABASE_URL: file:local.db
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # run any `bun` or `bunx` command
      - run: bun install
      - name: Prepare playwright
        run: bunx playwright install
      - name: Run all Tests
        run: bun run test
        env:
          MAILPIT_DOMAIN: http://localhost:8025
          MAIL_FROM: noreply@shrtn.io
          ORIGIN: http://localhost:4173
      - name: Test SMTP
        run: bun run test:e2e:smtp
        env:
          MAILPIT_DOMAIN: http://localhost:8025 #Requiered for e2e api access
          MAIL_PROVIDER: smtp
          MAIL_HOST: localhost
          MAIL_PORT: 1025
          MAIL_FROM: noreply@shrtn.io
          ORIGIN: http://localhost:4173
  test-docker:
    name: Test and Build - Docker
    runs-on: ubuntu-latest
    services:
      mailpit:
        image: axllent/mailpit
        ports:
          - 8025:8025
          - 1025:1025
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Prepare playwright
        run: bunx playwright install
      - name: Build Docker Image
        run: docker build -t shrtn .
      - name: Start Container
        run: |
          docker run -d --name shrtn \
          -p 3001:3001 \
          -e MAILPIT_DOMAIN=http://host.docker.internal:8025 \
          shrtn
      - name: Run Tests
        run: bun run test:e2e:docker
      - name: Stop Container
        run: docker stop shrtn && docker rm shrtn
  test-cloudflare:
    name: Test and Build - Cloudflare
    runs-on: ubuntu-latest
    services:
      mailpit:
        image: axllent/mailpit
        ports:
          - 8025:8025
          - 1025:1025
    env:
      DATABASE_TYPE: d1
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # run any `bun` or `bunx` command
      - run: bun install
      - name: Prepare playwright
        run: bunx playwright install
      - name: Run all Tests
        run: bun run test:e2e:cloudflare
        env:
          MAILPIT_DOMAIN: http://localhost:8025
