name: Test
on: [push]
jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun run build
      - name: Prepare playwright
        run: bunx playwright install
      - name: Create Database
        run: bun run db:migrate
      - name: Run all Tests
        run: bun run test
        env:
          MAILPIT_DOMAIN: https://mailpit.dropanote.de
          MAIL_FROM: noreply@shrtn.io
          DATABASE_URL: file:./local.db
          ORIGIN: http://localhost:5173
